server:
  port: 8081

spring:
  application:
    name: grpc-demo-client
grpc:
  client:
    hello:
      address: 'static://127.0.0.1:9090'
      negotiationtype: plaintext
    helloBatch:
      address: 'static://127.0.0.1:9090'
      negotiationtype: plaintext
